### ISSUE TITLE
Wordpress must be able to send emails

### ISSUE THREAD

**Issue by koyan** [greenpeace/planet4-docker#20]
There are various solutions. Some have to do with the server setup and some with installing plugins that allow different ways to send emails. 
Suggestions @27Bslash6 how we should move forward? If the solution is server side, would you move it forward in the docker setup?

**Comment by 27Bslash6** [comment]
The solution I've used on the parent repository to these images was include exim in the container itself, which listens on localhost and handles email delivery natively and resiliently.

This provides an OS-native interface to third party SMTP servers, and was also configured to intercept all outgoing mail if the environment was development, which might save us accidentally emailing our entire user list on a developer's machine.
See: https://github.com/27Bslash6/docker/tree/master/nginx-php-exim

I removed the exim component for P4 in the process of trimming down potentially unwanted elements, with the intention of including it in a separate container at some point.  Maybe that point is soon?

This also requires advice as to any current SMTP system (SendGrid / Mailgun / Google / other) being used in other projects, and whether we want to tie into those.

Tagging @greenpeace/tam for advice

**Comment by lprevota** [comment]
> This also requires advice as to any current SMTP system (SendGrid / Mailgun / Google / other) being used in other projects, and whether we want to tie into those.

Infra Team is currently implementing external mail gateways in GCP, using MailGun as smtp relay. 

So you could use those gateways but need further discussion on purpose of mail to be sent, what need to be done with bounces, tracking, etc... and estimated numbers /day, /week, /months... to see if it match plans we signed up for. 

Other option would be to sign up with a dedicated P4 account at SendGrid or MailGun, for you to use their smtp relay or API.

**Comment by 27Bslash6** [comment]
Thanks for the advice @lprevota 
Speaking with Mark we're considering going the direct GCP mailer route fed by local mail queues to minimise moving parts.  I hope to schedule a look at this later in the week and will keep you updated.

**Comment by 27Bslash6** [comment]
SSMTP added to php-fpm container, new exim container created for managing queues.
Relaying to smtp-relay.gmail.com::587 by default, configurable via environment variable.
See #22
